displayName=Area Loot
author=Aiirik
description=Shows nearby ground loot in a panel and highlights selected item locations
tags=ground,loot,highlight,panel,area,drops,overlay,arealoot,
version= 1.5.0
plugins=com.arealoot.AreaLootPlugin
build=standard
